### ISSUE TITLE
Can not load multilingual model. (ERROR in huggingface transformers library)

### ISSUE THREAD

**Issue by javiabellan** [unum-cloud/uform#27]
At calling

```python
model = uform.get_model('unum-cloud/uform-vl-multilingual')
```

which calls [at line 293](https://github.com/unum-cloud/uform/blob/main/src/uform.py#L293)

```python
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')
```

generates the following error:

![fbe2d604-4648-4252-9cc2-2f092b9c6485](https://github.com/unum-cloud/uform/assets/31625296/828e2e47-b1c3-482e-aef5-2075b4e43bb2)

NOTE: I have the latest version of transformers lib (4.30.2)

**Comment by javiabellan** [comment]
I think the file `vocab.txt` is missing in https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/tree/main but i dont kown if this is the issue

**Comment by kimihailv** [comment]
Hello. I tried to load the model and tokenizer and everything was ok (I used the same version of transformers and the latest version of uform from pypi). Could you please reinstall `transformers` and `uform` and try again?

**Comment by ashvardanian** [comment]
@javiabellan, do you still experience this issue?
