### ISSUE TITLE
Releasing training dataset

### ISSUE THREAD

**Issue by skull8888888** [unum-cloud/uform#5]
First of all, great work and congrats on the release. I was wondering whether you are planning on releasing the cleaned up 4M dataset?

**Comment by kimihailv** [comment]
Hello. Thank you for your interest. We aren't going to release our training dataset. However we can reveal some details:

1) Our dataset consists of public available datasets: COCO, Visual Genome, SBU (~800k samples totally) + CC12M (3.2M)
2) We use CLIP scores for filtering, also we use some ideas for filtering from this paper https://arxiv.org/pdf/2207.07635.pdf

**Comment by PoetCoderJun** [comment]
> Hello. Thank you for your interest. We aren't going to release our training dataset. However we can reveal some details:
> 
> 1. Our dataset consists of public available datasets: COCO, Visual Genome, SBU (~800k samples totally) + CC12M (3.2M)
> 2. We use CLIP scores for filtering, also we use some ideas for filtering from this paper https://arxiv.org/pdf/2207.07635.pdf

Will there be a paper released later?
