### ISSUE TITLE
ModuleNotFoundError: No module named 'uform.gen_model'; 'uform' is not a package

### ISSUE THREAD

**Issue by karthikra** [unum-cloud/uform#63]
Trying this from the example provided

**Comment by kimihailv** [comment]
Can you please show the output of this command:

```bash
pip show uform
```

**Comment by karthikra** [comment]
> Can you please show the output of this command:
> 
> ```shell
> pip show uform
> ```

Name: uform
Version: 0.4.8
Summary: Multi-Modal Transformers library for Semantic Search and other Vision-Language tasks
Home-page: 
Author: 
Author-email: Mikhail Kim <mike.kim@unum.cloud>, Vladimir Orshulevich <vladimir.orshulevich@unum.cloud>, Ash Vardanian <ash.vardanian@unum.cloud>

**Comment by karthikra** [comment]
> Can you please show the output of this command:
> 
> ```shell
> pip show uform
> ```

Name: uform
Version: 1.0.3
Summary: Multi-Modal Transformers library for Semantic Search and other Vision-Language tasks
Home-page: 
Author: 
Author-email: Mikhail Kim <mike.kim@unum.cloud>, Vladimir Orshulevich <vladimir.orshulevich@unum.cloud>, Ash Vardanian <ash.vardanian@unum.cloud>


This is with the latest
