### ISSUE TITLE
Problem with Batch Input

### ISSUE THREAD

**Issue by afsaneh-ebrahimi** [unum-cloud/uform#72]
Hi,

Thanks for your repository. I have a question, when I want to give a batch of data points to the model I face with the following error:

for batch_idx, (inputs, targets) in enumerate(test_loader):
----> 9   image_info = model.preprocess_image(inputs).unsqueeze(0)
     10 #image_info = model.preprocess_image(images).unsqueeze(0)

2 frames
[/usr/local/lib/python3.10/dist-packages/uform/models.py](https://localhost:8080/#) in convert_to_rgb(image)
     21 # lambda is not pickable
     22 def convert_to_rgb(image):
---> 23     return image.convert("RGB")

AttributeError: 'Tensor' object has no attribute 'convert'

**Comment by kimihailv** [comment]
Hello. As I understand, `inputs` is tensor, yes? model.preprocess_image expects PIL image(s)
