### ISSUE TITLE
how can I decode image feature to text?

### ISSUE THREAD

**Issue by zshnb** [unum-cloud/uform#77]
as the code in README, when I get image_features, how can I decode image_features to text?

**Comment by ashvardanian** [comment]
Hi @zshnb! Which model and which part of the README are you referring to?

**Comment by zshnb** [comment]
> Hi @zshnb! Which model and which part of the README are you referring to?

Hi here
<img width="881" alt="image" src="https://github.com/unum-cloud/uform/assets/17894980/46d8b15b-2945-4859-8ab6-46e73e6b74b5">
after output the feature, how can I decode feature to text?

**Comment by ashvardanian** [comment]
That can't be done with those models. You can only use those features for reranking. 

If you are looking to produce text afterwards, look into the generative model mentioned lower in the file 🤗
