### ISSUE TITLE
No module named 'uform.models' 

### ISSUE THREAD

**Issue by ake020675** [unum-cloud/uform#79]
the problem is:
      Traceback (most recent call last):
        File "/content/ugen-image-captioning-hf/app.py", line 2, in <module>
          from uform import gen_model
        File "/usr/local/lib/python3.10/dist-packages/uform/gen_model.py", line 18, in <module>
          from uform.models import VisualEncoder
      ModuleNotFoundError: No module named 'uform.models'

Maybe this line should be  "from uform.torch_models import VisualEncoder"?

**Comment by ashvardanian** [comment]
Yes, @ake020675, it should! Can you please open a pull request?

**Comment by ashvardanian** [comment]
Thank you, @ake020675!

**Comment by ake020675** [comment]
> Yes, @ake020675, it should! Can you please open a pull request?

I tested the new code and it worked.
It's my first time to pull request. Hope i did everything right

**Comment by ashvardanian** [comment]
Yes, it was great, @ake020675! Don’t hesitate to submit patches to USearch, StringZilla, SimSIMD or other related projects I maintain. Community makes open source better 🤗
