### ISSUE TITLE
Can't load model uform-vl-multilingual-v2

### ISSUE THREAD

**Issue by polm-stability** [unum-cloud/uform#90]
When trying to load the `unum-cloud/uform-vl-multilingual-v2` model using the example code from its README, I get this error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/blah/usearch-images/env/lib/python3.12/site-packages/uform/__init__.py", line 187, in get_model
    return get_model_onnx(model_name, device=device, token=token, modalities=modalities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/blah/usearch-images/env/lib/python3.12/site-packages/uform/__init__.py", line 155, in get_model_onnx
    encoder = TextEncoder(modality_paths.get(Modality.TEXT_ENCODER), device=device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/blah/usearch-images/env/lib/python3.12/site-packages/uform/onnx_encoders.py", line 109, in __init__
    self.text_encoder_session = ort.InferenceSession(
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/blah/usearch-images/env/lib/python3.12/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 405, in __init__
    raise TypeError(f"Unable to load from type '{type(path_or_bytes)}'")
TypeError: Unable to load from type '<class 'NoneType'>'
```

Example code, for reference:

```
import uform

model, processor = uform.get_model('unum-cloud/uform-vl-multilingual-v2')
```

Has something changed so this model is no longer supported or something? I originally ran into this issue with [the streamlit demo](https://github.com/ashvardanian/usearch-images), though I notice that seems a bit dated.

**Comment by ashvardanian** [comment]
Hey @polm-stability! Yes, can you please upgrade to the v3 models for embeddings? The weights would be the same, but the files under the new handle are organized in a way compatible with the new codebase. Please let me know if it works 🤗

**Comment by polm-stability** [comment]
Sorry for the delayed followup, thanks for the clarification. 

Is the v3 model [unum-cloud/uform3-image-text-multilingual-base](https://huggingface.co/unum-cloud/uform3-image-text-multilingual-base)? It looks that way but given how different the name was I wasn't sure if it was a new version or a separate model. 

In either case, I was able to load that model successfully using the README instructions.

If v2 is no longer supported maybe the README for it should be updated?

**Comment by ashvardanian** [comment]
> Is the v3 model [unum-cloud/uform3-image-text-multilingual-base](https://huggingface.co/unum-cloud/uform3-image-text-multilingual-base)?

Yes 🤗
